# Generated by Django 4.2.7 on 2023-12-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('ename', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=30)),
                ('sal', models.IntegerField()),
                ('comm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptNo', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=50)),
                ('loc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empNo', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=30)),
                ('mgr', models.IntegerField()),
                ('sal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('losal', models.IntegerField()),
                ('hisal', models.IntegerField()),
            ],
        ),
    ]
